### ISSUE TITLE
container image is veeery large...

### ISSUE THREAD

**Issue by marscher** [omnia-md/centos5-build-box#2]
around ~2.5 GB, is this really necessary?

**Comment by jchodera** [comment]
It's built on [`holy-build-box`](http://phusion.github.io/holy-build-box/), which attempts to keep the container small and portable.

We also try to delete any files that aren't used after installation.

Not sure there's much that can easily be done here.

**Comment by jchodera** [comment]
The TeXLive installation itself is probably like 1GB.

**Comment by marscher** [comment]
Ok. Tex, Cuda etc. takes alot of space, I see.
